services:
  database:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
        - MYSQL_DATABASE=restfuldart
        - MYSQL_USER_FILE=/run/secrets/db_user
        - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=$$(cat $${MYSQL_ROOT_PASSWORD_FILE}) 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      retries: 60
      interval: 5s
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      backend-net:
        aliases:
          - mysql
    secrets:
        - db_user
        - db_password

  api:
    build: .
    container_name: api
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - PORT=8080
      - API_QUERIES_LIMIT=100
      - API_QUERIES_PAGE=1
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=alessandromaifredi
      - MYSQL_PASSWORD=851610
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
        required: true
        restart: always
    networks:
      backend-net:
        aliases:
          - api
    secrets:
        - db_user
        - db_password

networks:
  backend-net:
    driver: bridge

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
    mysql-volume: