version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_user
        - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_password
        - MONGO_INITDB_DATABASE=restfuldart
    volumes:
      - monongodb-volume:/data/db
    networks:
      mongo-net:
        aliases:
          - database
    secrets:
      - db_user
      - db_password

  api:
    build: .
    container_name: api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - PORT=8080
      - API_QUERIES_LIMIT=100
      - API_QUERIES_PAGE=1
      - MONGO_DART_DRIVER_HOST=database
      - MONGO_DART_DRIVER_PORT=27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      mongo-net:
        aliases:
          - api
    volumes:
        - restfuldart-volume:/app

networks:
  mongo-net:
    driver: bridge

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
    monongodb-volume:
    restfuldart-volume: